name: lofter_fixer
description: A Flutter app to remove watermarks using YOLO.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # 核心依赖
  tflite_flutter: ^0.10.4  # TensorFlow Lite 推理
  image: ^4.1.3            # 纯Dart图像处理 (比OpenCV更轻量)
  image_picker: ^1.0.7     # 选择图片
  file_picker: ^6.1.1      # 选择文件/保存路径
  path_provider: ^2.1.2    # 获取路径
  shared_preferences: ^2.2.2 # 保存设置
  permission_handler: ^11.3.0 # 权限管理

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # 注册资源
  assets:
    - assets/models/
    - assets/images/