name: lofter_repair_tool
description: A tool to remove watermarks using YOLO.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # 🤖 TFLite 模型运行库
  tflite_flutter: ^0.10.4
  # 🖼️ 图像处理库 (Dart版的OpenCV)
  image: ^4.1.7
  # 📂 文件选择器
  file_picker: ^8.0.0
  # 🔒 权限管理
  permission_handler: ^11.3.0
  # 💾 路径获取
  path_provider: ^2.1.2
  # 💅 UI 图标
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # 📦 资源注册
  assets:
    - assets/models/