name: lofter_fixer
description: A Lofter Watermark Remover
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # UI图标
  cupertino_icons: ^1.0.2
  # 权限管理 (核心)
  permission_handler: ^11.3.0
  # 文件/图片选择
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  # 提示框
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true