distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
# 👇👇👇 关键修改：将原来的 7.6.3 改为 8.0 👇👇👇
distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-all.zip