buildscript {
    ext.kotlin_version = '1.9.0' // 锁定 Kotlin 版本
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        // 锁定 Android 构建工具版本
        classpath 'com.android.tools.build:gradle:7.3.0'
        // 锁定 Kotlin 插件
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}