buildscript {
    ext.kotlin_version = '1.9.0' // 👈 强制指定 Kotlin 版本
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        // 👇 这里定义插件的“真身”和版本
        classpath 'com.android.tools.build:gradle:7.3.0' // 适配 Flutter 3.19 的稳定版 AGP
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}